// Provider registry: metadata for all supported LLM providers.
// kind: 'ollama' | 'anthropic' | 'gemini' | 'openai-compat'
// For openai-compat providers, all of OpenAI's Chat Completions API is used.

export const PROVIDERS = [
  // ── Local ──────────────────────────────────────────────────────────────────
  {
    id: 'ollama',
    name: 'Ollama',
    kind: 'ollama',
    description: 'Local models via Ollama runtime',
    requiresKey: false,
    baseUrlEditable: false, // configured via OllamaSetup separately
    presetModels: [], // dynamic from /api/tags
    allowCustomModel: true,
    badge: 'local',
  },

  // ── Native (custom adapters) ──────────────────────────────────────────────
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    kind: 'anthropic',
    description: 'Claude Opus / Sonnet / Haiku',
    requiresKey: true,
    keyPlaceholder: 'sk-ant-...',
    keyHelpUrl: 'https://console.anthropic.com/settings/keys',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.anthropic.com',
    presetModels: [
      'claude-opus-4-5',
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
      'claude-3-5-sonnet-latest',
      'claude-3-5-haiku-latest',
    ],
    allowCustomModel: true,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    kind: 'gemini',
    description: 'Gemini 2.5 Pro / Flash',
    requiresKey: true,
    keyPlaceholder: 'AIza...',
    keyHelpUrl: 'https://aistudio.google.com/apikey',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
    presetModels: [
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
    ],
    allowCustomModel: true,
  },

  // ── OpenAI-compatible ─────────────────────────────────────────────────────
  {
    id: 'openai',
    name: 'OpenAI',
    kind: 'openai-compat',
    description: 'GPT-4o, GPT-4o-mini, o1, o3-mini',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    keyHelpUrl: 'https://platform.openai.com/api-keys',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.openai.com/v1',
    presetModels: ['gpt-4o', 'gpt-4o-mini', 'o1', 'o1-mini', 'o3-mini', 'gpt-4-turbo'],
    allowCustomModel: true,
  },
  {
    id: 'groq',
    name: 'Groq',
    kind: 'openai-compat',
    description: 'Ultra-fast inference (Llama, Mixtral)',
    requiresKey: true,
    keyPlaceholder: 'gsk_...',
    keyHelpUrl: 'https://console.groq.com/keys',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    presetModels: [
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant',
      'mixtral-8x7b-32768',
      'gemma2-9b-it',
    ],
    allowCustomModel: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    kind: 'openai-compat',
    description: 'Cheap & strong reasoning',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    keyHelpUrl: 'https://platform.deepseek.com/api_keys',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.deepseek.com/v1',
    presetModels: ['deepseek-chat', 'deepseek-reasoner'],
    allowCustomModel: true,
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    kind: 'openai-compat',
    description: 'Grok with real-time data',
    requiresKey: true,
    keyPlaceholder: 'xai-...',
    keyHelpUrl: 'https://console.x.ai',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.x.ai/v1',
    presetModels: ['grok-2-latest', 'grok-2-1212', 'grok-beta'],
    allowCustomModel: true,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    kind: 'openai-compat',
    description: 'Mistral Large, Codestral',
    requiresKey: true,
    keyPlaceholder: '...',
    keyHelpUrl: 'https://console.mistral.ai/api-keys/',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    presetModels: [
      'mistral-large-latest',
      'mistral-small-latest',
      'codestral-latest',
      'open-mistral-nemo',
    ],
    allowCustomModel: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    kind: 'openai-compat',
    description: 'Sonar models with built-in web search',
    requiresKey: true,
    keyPlaceholder: 'pplx-...',
    keyHelpUrl: 'https://www.perplexity.ai/settings/api',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.perplexity.ai',
    presetModels: [
      'sonar-pro',
      'sonar',
      'sonar-reasoning',
      'sonar-reasoning-pro',
    ],
    allowCustomModel: true,
  },
  {
    id: 'together',
    name: 'Together AI',
    kind: 'openai-compat',
    description: 'Open-source model hosting (200+)',
    requiresKey: true,
    keyPlaceholder: '...',
    keyHelpUrl: 'https://api.together.ai/settings/api-keys',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.together.xyz/v1',
    presetModels: [
      'meta-llama/Llama-3.3-70B-Instruct-Turbo',
      'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
      'Qwen/Qwen2.5-72B-Instruct-Turbo',
      'deepseek-ai/DeepSeek-V3',
    ],
    allowCustomModel: true,
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    kind: 'openai-compat',
    description: 'Fast open-source model hosting',
    requiresKey: true,
    keyPlaceholder: 'fw_...',
    keyHelpUrl: 'https://fireworks.ai/account/api-keys',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
    presetModels: [
      'accounts/fireworks/models/llama-v3p3-70b-instruct',
      'accounts/fireworks/models/qwen2p5-72b-instruct',
      'accounts/fireworks/models/deepseek-v3',
    ],
    allowCustomModel: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    kind: 'openai-compat',
    description: 'Gateway to 300+ models',
    requiresKey: true,
    keyPlaceholder: 'sk-or-...',
    keyHelpUrl: 'https://openrouter.ai/keys',
    baseUrlEditable: true,
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    presetModels: [
      'anthropic/claude-3.5-sonnet',
      'openai/gpt-4o',
      'google/gemini-pro-1.5',
      'meta-llama/llama-3.3-70b-instruct',
    ],
    allowCustomModel: true,
  },

  // ── Self-host / custom ────────────────────────────────────────────────────
  {
    id: 'custom',
    name: 'Custom (OpenAI-compatible)',
    kind: 'openai-compat',
    description: 'LM Studio, LocalAI, vLLM, or any custom OpenAI-compatible endpoint',
    requiresKey: false, // key often optional for local servers
    keyPlaceholder: '(optional for local)',
    baseUrlEditable: true,
    defaultBaseUrl: 'http://localhost:1234/v1',
    presetModels: [],
    allowCustomModel: true,
    badge: 'custom',
  },
]

export function getProvider(id) {
  return PROVIDERS.find((p) => p.id === id) || PROVIDERS[0]
}
